version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "typescript"
        versions: ["<6.0.0"]
